- mnist_cnn/Makefile
- tests/test_dataset_creation.py
Reworked tests for the dataset creation. Also updated the Makefile:
With `make quick_data_and_training` the first 50 pictures of the mnist dataset are processed and trained, so that this functionality can be checked quick.
> Test tuning

- .gitignore
- dl_framework/architectures.py
- dl_framework/callbacks.py
- dl_framework/data.py
- dl_framework/model.py
- dl_framework/preprocessing.py
- mnist_cnn/Makefile
- mnist_cnn/calculate_normalization.py
- mnist_cnn/create_mnist_fft.py
- mnist_cnn/create_mnist_fft_sampled.py
- mnist_cnn/inspection.py
- mnist_cnn/preprocessing.py
- mnist_cnn/train_cnn.py
- mnist_cnn/utils.py
- mnist_cnn/visualize/Makefile
- mnist_cnn/visualize/visualize_predictions.py
- mnist_cnn/visualize/visualize_preprocessing.py
- tests/test_mnist_normalization.py
Mainly change to two channel. That implies changes to e.g. the architecture as well as to the view_transformation. also wrote some more functions, deleted doubling pieces of code and implemented a plotting function for the loss. Still not sure, what loss (validation or training) is plotted.
> Two channels

- dl_framework/utils.py
- mnist_cnn/Makefile
- mnist_cnn/train_cnn.py
- setup.py
Documentation for `train_cnn.py` and Documentation for `AvgStats`. Also some Pep8 changes
> Documentation

- .gitignore
- dl_framework/learner.py
- mnist_cnn/Makefile
- mnist_cnn/train_cnn.py
- mnist_cnn/visualize/Makefile
- mnist_cnn/visualize/visualize_predictions.py
Modified the `visualize_predictions` file, so that ten random pictures are produced. One has still the option to produce just a single picture with a specific index. Also added the option to interrupt the training with _strg_c_ with the possibility to save the progress and produce the usual plots or to discard the progress.
> Visualize pred

- .gitattributes
- dl_framework/callbacks.py
- dl_framework/learner.py
- dl_framework/logger.py
- dl_framework/loss_functions.py
- mnist_cnn/Makefile
- mnist_cnn/inspection.py
- mnist_cnn/train_cnn.py
- mnist_cnn/visualize/Makefile
- mnist_cnn/visualize/visualize_predictions.py
Implemented a logger callback, which sends telegram messages over a bot which contain the current Epoch and the current loss. Also it sends a message when the training starts and when the training ends.
The `.gitattributes` is part of a solution to prevent the bot api to be available on github, more more information look [here](https://stackoverflow.com/questions/6557467/can-git-ignore-a-specific-line).
Also it was necessary to rename the logger attribute of the learner. Now it is called log. It behaves the same way like before.
> Telegram Logger

- .gitattributes
- .gitignore
- dl_framework/logger.py
Removed the git filter system and added a `yaml file` for imports. Can be used for other imports as well.
> Better logger

- dl_framework/architectures.py
- dl_framework/callbacks.py
- dl_framework/data.py
- dl_framework/model.py
- gaussian_sources/Makefile
- gaussian_sources/create_fft_pairs.py
- gaussian_sources/fft_tests.py
- gaussian_sources/find_lr.py
- gaussian_sources/train_cnn.py
- gaussian_sources/visualize/visualize_predictions.py
- simulations/uv_simulations.py
- played around with architectures
- updated `SaveCallback` for `save_model` function and saving a different file each ten epochs
- pep8 changes for `data.py`
- changed `h5_dataset` for a variable, quadratic input size
- changed fft layer, but without doc string
- added creation and use of test data set for visualization
> Test datensatz

- gaussian_sources/Makefile
- gaussian_sources/find_lr.py
> Minor changes

- dl_framework/architectures.py
- dl_framework/data.py
- dl_framework/model.py
- gaussian_sources/Makefile
- gaussian_sources/create_fft_pairs.py
- gaussian_sources/find_lr.py
- gaussian_sources/inspection.py
- gaussian_sources/train_cnn.py
- gaussian_sources/visualize/Makefile
- gaussian_sources/visualize/visualize_predictions.py
- create a new architecture for training in fourier space
- modified class `h5_dataset` for handling fourier transformed target images
- out commented the `fft_shif`t in the fft layer and creating an `flatten` layer, which keeps the shape
- modified Makefile for the use of .makerc in dataset creation and fourier transformed images
- added option for fourier transformed images in `create_fft_pairs`
- revised `find_lr`
- reworked `visualize_predictions` for plotting with fourier transformed target images and outsourced the plotting functions. Problem is kind of cpu consuming, in this way it is not optimized
> Train in Fourier Space

- .gitignore
- simulations/gaussian_simulations.py
- simulations/uv_plots.py
- simulations/uv_simulations.py
- tests/test_dataset_creation.py
- tests/test_gaussian_simulations.py
- tests/test_uv_plots.py
- tests/test_uv_simulations.py
adding tests for simulations
standard image size is changed to 63 x 63 for symmetry reasons
fixing issue #42
> Simulations tests

- .gitignore
- dl_framework/learner.py
- gaussian_sources/find_lr.py
- gaussian_sources/train_cnn.py
- mnist_cnn/Makefile
- mnist_cnn/scripts/find_lr.py
- mnist_cnn/scripts/train_cnn.py
- tests/test_mnist/test_mnist.py
> Append callbacks

- dl_framework/architectures.py
- dl_framework/callbacks.py
- dl_framework/learner.py
- dl_framework/model.py
- setup.py
- added a data augmentation callback which rotates the amplitude and phase of target and true image by multiples of 90 degrees at the beginning of each batch
- added docstrings for `conv_amp` and `conv_phase`
- changed click version because of this error message
> ERROR: proj 0.2.0 has requirement click>=7.1.2, but you'll have click 7.0 which is incompatible.
> Data Augmentation

- gaussian_sources/Makefile
- gaussian_sources/find_lr.py
- gaussian_sources/inspection.py
- gaussian_sources/plot_loss.py
- gaussian_sources/visualize/save_predictions.py
- applied changes from `train_cnn.py` to `find_lr.py` and `plot_loss.py`
- To ensure the functionality of `plot_loss.py`, changes to the Makefile were also necessary, e.g. to get the image size
> Apply changes in getting the architetcure

- gaussian_sources/Makefile
- gaussian_sources/find_lr.py
- gaussian_sources/train_cnn.py
- tests/test_gaussian_sources/test_gaussian_sources.py
- added batch size argument from `.makerc` to `find_lr.py`
- deleted unused packages in `train_cnn.py`
- black8 changes for `find_lr.py` and `train_cnn.py`
- updated test for `find_lr.py`
> Add batch size click argument to find_lr and other small changes

- .gitignore
- .travis.yml
- dl_framework/architectures.py
- dl_framework/callbacks.py
- dl_framework/data.py
- dl_framework/inspection.py
- dl_framework/learner.py
- dl_framework/loss_functions.py
- gaussian_sources/create_fft_pairs.py
- gaussian_sources/inspection.py
- gaussian_sources/plot_loss.py
- gaussian_sources/visualize/Makefile
- gaussian_sources/visualize/mean_msssim.py
- gaussian_sources/visualize/save_predictions.py
- gaussian_sources/visualize/visualize_predictions.py
- mnist_cnn/Makefile
- mnist_cnn/scripts/create_fft_sampled.py
- mnist_cnn/scripts/create_mnist_fft.py
- mnist_cnn/scripts/find_lr.py
- mnist_cnn/scripts/plot_loss.py
- mnist_cnn/scripts/train_cnn.py
- mnist_cnn/scripts/utils.py
- mnist_cnn/scripts/visualize.py
- pytorch_msssim/__init__.py
- simulations/uv_simulations.py
- tests/test_mnist/test_mnist.py
- tests/test_simulations/test_uv_simulations.py
- tests/test_visualization/test_eval_plots.py
- utilities/travis_setup.sh
- Changed padding values, so that the image size during training does not change
- added latex plotting
> Use the same image size in filter_deep

- dl_framework/architectures.py
- dl_framework/utils.py
- gaussian_sources/Makefile
- gaussian_sources/train_cnn.py
As mentioned in the Outlook of my Thesis, the performance of Filter Deep could be improved by choosing the kernel size relative to the image size. For this, I created Filter Deep variable, which uses two functions for the kernel size and the padding in order to choose the kernel size as a fraction of the image size.
> Variable kernel size for Filter Deep

- dl_framework/learner.py
- dl_framework/loss_functions.py
Use of `getattr` for the loss functions in `dl_framework/learner.py`.
> Clean up loss functions in learner

- examples/default_eval_config.toml
- radionets/dl_framework/architecture.py
- radionets/dl_framework/architectures/res_exp.py
- radionets/dl_framework/callbacks.py
- radionets/dl_framework/inspection.py
- radionets/dl_framework/learner.py
- radionets/dl_framework/loss_functions.py
- radionets/dl_framework/model.py
- radionets/dl_training/scripts/start_training.py
- radionets/evaluation/contour.py
- radionets/evaluation/plotting.py
- radionets/evaluation/scripts/start_evaluation.py
- radionets/evaluation/train_inspection.py
- radionets/evaluation/utils.py
- setup.py
Added contour plots and the difference between the areas of the prediction and the truth as evaluation methods. Also some black changes and small convenience changes.
> Added contour plots as evaluation method

- examples/.rc/simulations/simulation_extended_gaussians.toml
- examples/.rc/simulations/simulation_fourier_amp.toml
- examples/.rc/simulations/simulation_fourier_real.toml
- examples/.rc/simulations/simulation_local.toml
- examples/.rc/simulations/simulation_mix.toml
- examples/.rc/simulations/simulation_pointlike_gaussians.toml
- examples/.rc/simulations/simulation_pointsources.toml
- examples/.rc/simulations/simulation_source_list.toml
- radionets/dl_framework/callbacks.py
- radionets/dl_framework/inspection.py
- radionets/evaluation/plotting.py
- radionets/evaluation/train_inspection.py
- radionets/evaluation/utils.py
- radionets/simulations/sampling.py
- radionets/simulations/simulate.py
- radionets/simulations/utils.py
- Added interpolation
- Some plotting changes for the paper
> Plotting changes for the paper

- examples/.rc/benchmark/sim_benchmark.toml
- examples/.rc/simulations/simulation_extended_gaussians.toml
- examples/.rc/simulations/simulation_fourier_amp.toml
- examples/.rc/simulations/simulation_fourier_real.toml
- examples/.rc/simulations/simulation_local.toml
- examples/.rc/simulations/simulation_mix.toml
- examples/.rc/simulations/simulation_pointlike_gaussians.toml
- examples/.rc/simulations/simulation_pointsources.toml
- examples/.rc/simulations/simulation_source_list.toml
- examples/default_simulation_config.toml
- radionets/simulations/gaussians.py
- radionets/simulations/simulate.py
- radionets/simulations/utils.py
Added noise level keyword to toml file, so it can be varied better for different datasets. Also changed the default and testing toml files.
> Add Noise level keyword to toml files

- radionets/dl_framework/architectures/res_exp.py
- radionets/dl_framework/loss_functions.py
- radionets/evaluation/train_inspection.py
Small fixes for uncertainty training:
- Smaller value for GeneralELU
- splitted L1 loss functions for uncertainty training with weight on phase
- fix `get_prediction` for combined architectures
> Small Uncertainty changes

- environment.yml
- setup.py
Tests failed because of torchvision version 0.10.0 (see [here](https://github.com/radionets-project/radionets/runs/3279679799?check_suite_focus=true)), so i restricted the version to below 0.10.0.
> Restriction on torchvision

- radionets/dl_framework/data.py
- radionets/dl_framework/model.py
- radionets/dl_training/scripts/start_training.py
- radionets/evaluation/plotting.py
- radionets/evaluation/utils.py
- Add error for wrongly named bundle files
- Delete old label and font sizes
- Update some docstrings
> Small fixes

- examples/default_eval_config.toml
- examples/default_simulation_config.toml
- radionets/evaluation/plotting.py
- radionets/evaluation/train_inspection.py
- radionets/evaluation/utils.py
- radionets/simulations/gaussians.py
- radionets/simulations/sampling.py
- radionets/simulations/simulate.py
- radionets/simulations/utils.py
- radionets/simulations/uv_simulations.py
- setup.py
- tests/evaluate.toml
- tests/simulate.toml
- save values after evaluation
- add values for white_noise
- add bandwidths
> Save evaluation values

- radionets/dl_training/scripts/start_training.py
- radionets/evaluation/train_inspection.py
- setup.py
add option to perform fine-tuning of a pretrained model
> add fine tuning option

- radionets/dl_framework/callbacks.py
The extra dimension is gone and now also fixed in the comet callback
> Fix comet callback

- .pre-commit-config.yaml
- README.md
- radionets/dl_framework/architectures/unc_archs.py
- radionets/dl_framework/model.py
- setup.py
- tests/test_evaluation.py
- added pre-commits as in `pyvisgen`
- added warning to `even_better_symmetry` function if odd image sizes are used
- added test for `even_better_symmetry` function
ToDo:
> pre-commits and symmetry layer

- CITATION.cff
Added a CITATION.cff file for easy citation.
> Easier citation of repository

- docs/changes/129.feature.rst
- radionets/evaluation/contour.py
- radionets/evaluation/plotting.py
- radionets/evaluation/scripts/start_evaluation.py
- radionets/evaluation/train_inspection.py
- radionets/evaluation/utils.py
- tests/evaluate.toml
- tests/test_evaluation.py
- added creation of uncertainty plots
- changed creation and saving/reading of predictions to `dicts`
- prediction dicts have 3 or 4 entries depending on uncertainty
- added `scaled` option to `get_ifft`
I'm open to improvements, maybe some outsourcing?
ToDo:
> Add creation of uncertainty plots

- docs/changes/142.maintenance.rst
- radionets/dl_framework/data.py
- radionets/dl_training/scripts/start_training.py
- radionets/dl_training/utils.py
- radionets/evaluation/jet_angle.py
- tests/test_training.py
consistent use of batch_size
fixes #128
> change bs to batch_size

- docs/changes/149.bugfix.rst
- radionets/dl_framework/callbacks.py
- radionets/evaluation/utils.py
- calculate normalization only on non-zero pixels
- fix typo in rescaling operation
> Fix mean normalization method

- docs/changes/151.feature.rst
- radionets/evaluation/plotting.py
- radionets/evaluation/train_inspection.py
- radionets/evaluation/utils.py
- made sure 1 is the center of one bin for `histogram_area` and `histogram_intensity`
- add color to legend in histograms, for example here ![example plot](https://user-images.githubusercontent.com/23259659/222467334-f6a99838-eb01-4859-bd36-4c5de50c27c1.png)
> Better binning and legend

- docs/changes/154.maintenance.rst
- radionets/dl_framework/architectures/res_exp.py
- radionets/dl_framework/architectures/unc_archs.py
- radionets/dl_framework/data.py
- radionets/dl_framework/model.py
- radionets/dl_training/scripts/start_training.py
- radionets/dl_training/utils.py
- radionets/evaluation/train_inspection.py
- radionets/evaluation/utils.py
- tests/evaluate.toml
- tests/test_evaluation.py
- tests/test_training.py
- Delete `amp_phase` and `source_list` from `h5_dataset`
- Update colorbar label
> Small improvements

- docs/changes/155.bugfix.rst
- docs/changes/155.feature.rst
- radionets/dl_framework/architectures/res_exp.py
- radionets/dl_framework/architectures/unc_archs.py
- radionets/evaluation/plotting.py
- radionets/evaluation/scripts/start_evaluation.py
- radionets/evaluation/train_inspection.py
- radionets/evaluation/utils.py
- replaced variance before sampling with standard deviation
- removed too high values in GeneralELU
- used InstanceNorm in `unc_archs.py`
- added eval methods for sampled uncertainty
> Fix sampling and improve uncertainty evaluation

- docs/changes/164.bugfix.rst
- radionets/evaluation/train_inspection.py
- radionets/evaluation/utils.py
- Compute uncertainty histogram on source pixels only
- Check for existing sampling file before generating
- proper error propagation after using a normalization
> Uncertainty fixes

- docs/changes/165.feature.rst
- radionets/dl_framework/callbacks.py
- radionets/dl_framework/model.py
- radionets/evaluation/train_inspection.py
- radionets/evaluation/utils.py
- tests/test_evaluation.py
- Add new normalizing method that normalizes every image
- Add saving options for more evaluation methods
> Normalize images

- docs/changes/192.feature.rst
- src/radionets/architecture/layers.py
- tests/test_architecture_layers.py
Adding convolution layers which are specialized for complex input data.
> Complex layers

- docs/changes/195.feature.rst
- src/radionets/architecture/archs.py
- src/radionets/core/loss_functions.py
- src/radionets/evaluation/utils.py
This allows future architectures to also return other values that may be used by loss functions.
> Return prediction as dictionaries

- docs/changes/193.optimization.rst
- src/radionets/core/callbacks.py
- src/radionets/core/logging.py
- src/radionets/core/model.py
- src/radionets/evaluation/jets.py
- src/radionets/evaluation/scripts/start_evaluation.py
- src/radionets/evaluation/train_inspection.py
- src/radionets/plotting/inspection.py
- src/radionets/training/utils.py
- Allow `setup_logger` function to accept namespaces
- Allow `setup_logger` function to set logging level, default is now INFO
> Set logging level to INFO as default, get rid of DEBUG output

- docs/changes/198.feature.rst
- src/radionets/architecture/__init__.py
- src/radionets/architecture/archs.py
- src/radionets/architecture/blocks.py
- src/radionets/core/callbacks.py
- src/radionets/core/learner.py
Add implementation of ComplexSRResNet utilizing ComplexResBlocks (ComplexConv2d, ComplexInstancenorm2d, ComplexPReLU)
> add complex srresnet
